#pragma once

enum class Event {
    START_TRACKING,
    STOP_TRACKING,
    START_SLEWING,
    STOP_SLEWING,

    START_CAPTURING,
    STOP_CAPTURING,
    INCREASE_EXPOSURE_TIME,
    DECREASE_EXPOSURE_TIME,
    
    // Screen
    TOGGLE_BOTTOM_ROW,
    TOGGLE_TOP_ROW,

    // Manual Control
    MANUAL_SLEW_RA,
    MANUAL_SLEW_ARA,

    MOTOR_TEST,
    BUTTON_HELD,
    UNKNOWN,
    NONE
};
