#pragma once

enum class Event {
    SET_QUARTER_STEP,
    SET_HALF_STEP,
    SET_FULL_STEP,
    START_MOTOR,
    STOP_MOTOR,
    CHANGE_MOTOR_DIRECTION,
    INCREASE_EXPOSURE_TIME,
    DECREASE_EXPOSURE_TIME,
    START_CAPTURING,
    STOP_CAPTURING,
    BUTTON_HELD,
    UNKNOWN,
    NONE
};
